CREATE TABLE IF NOT EXISTS sync_checkpoints (
  chain TEXT NOT NULL,
  component TEXT NOT NULL,
  interval TEXT NOT NULL,
  last_height BIGINT,
  last_bucket_time TIMESTAMPTZ,
  status TEXT,
  error_message TEXT,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (chain, component, interval)
);

CREATE TABLE IF NOT EXISTS metric_registry (
  id SERIAL PRIMARY KEY,
  metric_name TEXT NOT NULL,
  chain TEXT NOT NULL,
  factor TEXT NOT NULL,
  module_path TEXT NOT NULL,
  function_name TEXT NOT NULL,
  interval TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  version TEXT NOT NULL DEFAULT 'v1',
  output_table TEXT NOT NULL,
  dependencies JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(metric_name, chain, interval, version)
);

CREATE TABLE IF NOT EXISTS btc_blocks_raw (
  height BIGINT PRIMARY KEY,
  block_hash TEXT UNIQUE,
  previous_block_hash TEXT,
  block_time TIMESTAMPTZ,
  median_time TIMESTAMPTZ,
  tx_count INTEGER,
  size BIGINT,
  stripped_size BIGINT,
  weight BIGINT,
  difficulty NUMERIC,
  chainwork TEXT,
  version INTEGER,
  merkle_root TEXT,
  raw_json JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS btc_primitive_block (
  height BIGINT PRIMARY KEY,
  block_hash TEXT,
  block_time TIMESTAMPTZ,
  median_time TIMESTAMPTZ,
  tx_count INTEGER,
  non_coinbase_tx_count INTEGER,
  total_out_sat BIGINT,
  total_fee_sat BIGINT,
  subsidy_sat BIGINT,
  issued_sat BIGINT,
  miner_revenue_sat BIGINT,
  input_count INTEGER,
  output_count INTEGER,
  block_size_bytes BIGINT,
  block_weight_wu BIGINT,
  block_vsize_vb BIGINT,
  difficulty NUMERIC,
  chainwork TEXT,
  cumulative_supply_sat NUMERIC,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS btc_primitive_30m (
  bucket_start_utc TIMESTAMPTZ PRIMARY KEY,
  open_time_ms BIGINT,
  first_height BIGINT,
  last_height BIGINT,
  block_count INTEGER,
  first_block_time_utc TIMESTAMPTZ,
  last_block_time_utc TIMESTAMPTZ,
  issued_sat_30m NUMERIC,
  fees_sat_30m NUMERIC,
  miner_revenue_sat_30m NUMERIC,
  supply_total_sat NUMERIC,
  block_reward_sat_avg NUMERIC,
  halving_epoch INTEGER,
  total_out_sat_30m NUMERIC,
  total_fee_sat_30m NUMERIC,
  transferred_sat_30m NUMERIC,
  transferred_btc_30m NUMERIC,
  tx_count_30m INTEGER,
  non_coinbase_tx_count_30m INTEGER,
  input_count_30m INTEGER,
  output_count_30m INTEGER,
  tx_rate_per_sec_30m NUMERIC,
  block_size_total_bytes_30m NUMERIC,
  block_size_mean_bytes_30m NUMERIC,
  block_weight_total_wu_30m NUMERIC,
  block_weight_mean_wu_30m NUMERIC,
  block_vsize_total_vb_30m NUMERIC,
  tx_size_total_bytes_30m NUMERIC,
  tx_size_mean_bytes_30m NUMERIC,
  block_interval_mean_sec_30m NUMERIC,
  block_interval_median_sec_30m NUMERIC,
  avg_fee_sat_30m NUMERIC,
  median_fee_sat_30m NUMERIC,
  avg_feerate_sat_vb_30m NUMERIC,
  min_feerate_sat_vb_30m NUMERIC,
  max_feerate_sat_vb_30m NUMERIC,
  utxo_increase_30m NUMERIC,
  utxo_count_total NUMERIC,
  utxo_size_inc_bytes_30m NUMERIC,
  utxo_set_size_total_bytes NUMERIC,
  spent_output_count_30m NUMERIC,
  created_output_count_30m NUMERIC,
  segwit_tx_count_30m INTEGER,
  segwit_share_30m NUMERIC,
  sw_total_size_bytes_30m NUMERIC,
  sw_total_weight_wu_30m NUMERIC,
  difficulty_last NUMERIC,
  chainwork_last TEXT,
  hashrate_est_last NUMERIC,
  hashrate_est_mean_30m NUMERIC,
  best_block_height_last BIGINT,
  open_price_usd NUMERIC,
  high_price_usd NUMERIC,
  low_price_usd NUMERIC,
  close_price_usd NUMERIC,
  market_cap_usd NUMERIC,
  onchain_volume_usd_raw_30m NUMERIC,
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS btc_nvt_30m (
  bucket_start_utc TIMESTAMPTZ PRIMARY KEY,
  price_usd NUMERIC,
  supply_total_sat NUMERIC,
  market_cap_usd NUMERIC,
  transferred_sat_30m NUMERIC,
  transferred_value_usd NUMERIC,
  nvt_raw NUMERIC,
  source_start_height BIGINT,
  source_end_height BIGINT,
  version TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS btc_nvt_1h (
  bucket_start_utc TIMESTAMPTZ PRIMARY KEY,
  price_usd NUMERIC,
  supply_total_sat NUMERIC,
  market_cap_usd NUMERIC,
  transferred_sat_30m NUMERIC,
  transferred_value_usd NUMERIC,
  nvt_raw NUMERIC,
  source_start_height BIGINT,
  source_end_height BIGINT,
  version TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_metric_registry_chain_factor_enabled
ON metric_registry(chain, factor, enabled);
